// <auto-generated />
using System;
using FitBox.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitBox.Migrations
{
    [DbContext(typeof(FitDbContext))]
    [Migration("20240804233714_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitBox.Models.Ingrediente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ingredientes");
                });

            modelBuilder.Entity("FitBox.Models.Marmita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataDeCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataDoConsumo")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Favorita")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StatusDeConsumo")
                        .HasColumnType("bit");

                    b.Property<int>("TamanhoRecipiente")
                        .HasColumnType("int");

                    b.Property<bool>("Verdura")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Marmitas");
                });

            modelBuilder.Entity("FitBox.Models.MarmitaIngrediente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IngredienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MarmitaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IngredienteId");

                    b.HasIndex("MarmitaId");

                    b.ToTable("MarmitasIngredientes");
                });

            modelBuilder.Entity("FitBox.Models.MarmitaIngrediente", b =>
                {
                    b.HasOne("FitBox.Models.Ingrediente", "Ingrediente")
                        .WithMany("Marmitas")
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitBox.Models.Marmita", "Marmita")
                        .WithMany("MarmitasIngredientes")
                        .HasForeignKey("MarmitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");

                    b.Navigation("Marmita");
                });

            modelBuilder.Entity("FitBox.Models.Ingrediente", b =>
                {
                    b.Navigation("Marmitas");
                });

            modelBuilder.Entity("FitBox.Models.Marmita", b =>
                {
                    b.Navigation("MarmitasIngredientes");
                });
#pragma warning restore 612, 618
        }
    }
}
