// <auto-generated />
using System;
using FitBox.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitBox.Migrations
{
    [DbContext(typeof(FitDbContext))]
    [Migration("20240804231157_UpdateModelWithComplexTypes")]
    partial class UpdateModelWithComplexTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitBox.Models.Ingrediente", b =>
                {
                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int?>("ReceitasId")
                        .HasColumnType("int");

                    b.HasKey("Nome");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.HasIndex("ReceitasId");

                    b.ToTable("Ingredientes");
                });

            modelBuilder.Entity("FitBox.Models.Marmita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataDeCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataDoConsumo")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Favorita")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StatusDeConsumo")
                        .HasColumnType("bit");

                    b.Property<int>("TamanhoRecipiente")
                        .HasColumnType("int");

                    b.Property<bool>("Verdura")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Marmitas");
                });

            modelBuilder.Entity("FitBox.Models.Receitas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Receitas");
                });

            modelBuilder.Entity("FitBox.Models.Ingrediente", b =>
                {
                    b.HasOne("FitBox.Models.Receitas", null)
                        .WithMany("Ingredientes")
                        .HasForeignKey("ReceitasId");
                });

            modelBuilder.Entity("FitBox.Models.Marmita", b =>
                {
                    b.OwnsOne("FitBox.Models.Carboidrato", "Carboidrato", b1 =>
                        {
                            b1.Property<Guid>("MarmitaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Quantidade")
                                .HasColumnType("int");

                            b1.Property<string>("Tipo")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("MarmitaId");

                            b1.ToTable("Marmitas");

                            b1.WithOwner()
                                .HasForeignKey("MarmitaId");
                        });

                    b.OwnsOne("FitBox.Models.Proteina", "Proteina", b1 =>
                        {
                            b1.Property<Guid>("MarmitaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Quantidade")
                                .HasColumnType("int");

                            b1.Property<string>("Tipo")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("MarmitaId");

                            b1.ToTable("Marmitas");

                            b1.WithOwner()
                                .HasForeignKey("MarmitaId");
                        });

                    b.Navigation("Carboidrato")
                        .IsRequired();

                    b.Navigation("Proteina")
                        .IsRequired();
                });

            modelBuilder.Entity("FitBox.Models.Receitas", b =>
                {
                    b.Navigation("Ingredientes");
                });
#pragma warning restore 612, 618
        }
    }
}
